version: "3"

services:
   influxdb_emon:
      image: hypriot/rpi-influxdb
      ports: 
         - "8089:8086"
      container_name: influxdb
      restart: always
      environment:
         - INFLUXDB_INIT_PWD= "admin"
         - PRE_CREATE_DB= emon
      volumes:
         - ./sm-timeseries_database_sds/data:/var/lib/influxdb
      networks:
         dial:
            ipv4_address: 172.18.0.2
      logging:
        driver: syslog
        options:
            tag: docker-influxdb


   grafana_emon:
      image: grafana/grafana
      ports: 
         - "3000:3000"
      container_name: grafana
      restart: always
      volumes:
         - grafana-db:/var/lib/grafana
         - grafana-log:/var/log/grafana
         - grafana-conf:/etc/grafana
      environment:
         - GF_AUTH_DISABLE_LOGIN_FORM=true
         - GF_AUTH_ANONYMOUS_ENABLED=true
         - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
         - GF_SECURITY_ALLOW_EMBEDDING=true
         # - GF_DATABASE_TYPE=influxdb
         # - GF_DATABASE_HOST=http://172.18.0.2:8086
         # - GF_DATABASE_NAME=emon

      networks:
          dial:
             ipv4_address: 172.18.0.3
      logging:
          driver: syslog
          options:
             tag: docker-grafana             
      depends_on:
           - influxdb_emon

   
   data_collection_python:
      build: ./sm-temperature_monitoring_dc
      container_name: read_data
      privileged: true
      restart: always
      volumes:
           - ./sm-temperature_monitoring_dc/code:/app/
         #   - ./sm-temperature_monitoring_dc/config:/app/config
      networks:
          dial:
             ipv4_address: 172.18.0.9
      logging:
          driver: syslog
          options:
            tag: docker-temperature-dc
      depends_on:
           - influxdb_emon
           - cherry_server
           - mosquitto_emon


   mosquitto_emon:
       image: pascaldevink/rpi-mosquitto
       ports:
           - "1883:1883"
       container_name: mosquitto
       restart: always
       volumes:
           - ./mqtt_broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
           - ./mqtt_broker/data:/mosquitto/data
           - ./mqtt_broker/log:/mosquitto/log
       logging:
           driver: syslog
           options:
               tag: docker-mqtt
       networks:
            dial:
               ipv4_address: 172.18.0.4

   cherry_server:
      image: server:v1
      build: ./sm-user_interface_config
      privileged: True
      ports: 
         - "8080:8080"
      container_name: cherry_server
      restart: always
      volumes:
         - ./sm-user_interface_config/app:/app
      logging:
           driver: syslog
           options:
               tag: docker-cherry_server
      depends_on:
           - mosquitto_emon
      networks:
         dial:
            ipv4_address: 172.18.0.7




networks:
     dial:
        ipam:
          config:
             - subnet: 172.18.0.0/16

volumes:
     grafana-db:
        driver: local
     grafana-log:
        driver: local
     grafana-conf:
        driver: local